# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: mik botol

on:
  schedule:
    - cron: '0 0 * * *'
    - cron: '1 6 * * *'
    - cron: '2 12 * * *'
    - cron: '3 18 * * *'
  workflow_dispatch:

permissions:
  contents: write

env:
  TOKEN : ${{ secrets.SMORT_TOKEN }}
  SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
  SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  itsshaunthesheep:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: install ffmpeg
      run: sudo apt install ffmpeg

    - name: write secrets and make queue.txt
      run: |
        touch .env
        touch queue.txt
        echo "SMORT_TOKEN=$TOKEN" >> .env
        echo 'WORKSPACE="actions"' >> .env
        echo "SPOTIFY_CLIENT_ID=$SPOTIFY_CLIENT_ID" >> .env
        echo "SPOTIFY_CLIENT_SECRET=$SPOTIFY_CLIENT_SECRET" >> .env

    - name: run bot
      run: python music.py
